export const AUTH_IN = 'AUTH_IN';
export const AUTH_OUT = 'AUTH_OUT';

export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';

export const COUNTRIES_LOAD = 'COUNTRIES_LOAD';
export const COUNTRIES_SEARCH = 'COUNTRIES_SEARCH';

export const PHONECODES_LOAD = 'PHONECODES_LOAD';
export const PHONECODE_AND_ID_UPDATE = 'PHONECODE_AND_ID_UPDATE';

export const PHOTO_UPDATE_CABINET = 'PHOTO_UPDATE_CABINET';
export const PHOTO_UPDATE_CV = 'PHOTO_UPDATE_CV';

export const PHOTO_UPLOAD_CABINET = 'PHOTO_UPLOLAD_CABINET';
export const PHOTO_UPLOAD_CV = 'PHOTO_UPLOAD_CV';
export const DELETE_PHOTO_IN_CONSTRUCTOR_CV = 'DELETE_PHOTO_IN_CONSTRUCTOR_CV';

export const PHOTO_FAILED_CABINET = 'PHOTO_FAILED_CABINET';
export const PHOTO_FAILED_CV = 'PHOTO_FAILED_CV';

export const POSITIONS_LOAD = 'POSITIONS_LOAD';

export const CHANGE_DIRTY_STATUS_FORM_PD = 'CHANGE_DIRTY_STATUS_FORM_PD';
export const RESET_DIRTY_STATUS_FORM_PD = 'RESET_DIRTY_STATUS_FORM_PD';

export const PERSONALDETAILS_LOADING_ON = 'PERSONALDETAILS_LOADING_ON';
export const PERSONALDETAILS_LOADING_OFF = 'PERSONALDETAILS_LOADING_OFF';
export const PERSONALDETAILS_UPDATE = 'PERSONALDETAILS_UPDATE';

export const LINK_IS_CLICKED = 'LINK_IS_CLICKED';
export const LINK_IS_NOT_CLICKED = 'LINK_IS_NOT_CLICKED';

export const MODAL_IS_OPENED = 'MODAL_IS_OPENED';
export const MODAL_IS_CLOSED = 'MODAL_IS_CLOSED';

export const INVALID_UPLOAD_PHOTO = 'INVALID_UPLOAD_PHOTO';
export const UPLOADED_PHOTO = 'UPLOADED_PHOTO';

export const ALL_CV_LOAD = 'ALL_CV_LOAD';
export const ALL_CV_LOADING_ON = 'ALL_CV_LOADING_ON';
export const ALL_CV_LOADING_OFF = 'ALL_CV_LOADING_OFF';

export const CHANGE_DIRTY_STATUS_IN_CONSTRUCTOR_CV = 'CHANGE_DIRTY_STATUS_IN_CONSTRUCTOR_CV';
export const RESET_DIRTY_STATUS_IN_CONSTRUCTOR_CV = 'RESET_DIRTY_STATUS_IN_CONSTRUCTOR_CV';

export const CONSTRUCTOR_CV_LOADING_ON = 'CONSTRUCTOR_CV_LOADING_ON';
export const CONSTRUCTOR_CV_LOADING_OFF = 'CONSTRUCTOR_CV_LOADING_OFF';
export const UPDATE_FIELD_IN_CONTACTS_CONSTRUCTOR_CV = 'UPDATE_FIELD_IN_CONTACTS_CONSTRUCTOR_CV';
export const CLEAR_FIELDS_IN_CONTACTS_CONSTRUCTOR_CV = 'CLEAR_FIELDS_IN_CONTACTS_CONSTRUCTOR_CV';
export const UPDATE_FIELD_IN_ABOUTYOURSELF_CONSTRUCTOR_CV =
  'UPDATE_FIELD_IN_ABOUTYOURSELF_CONSTRUCTOR_CV';
export const CLEAR_FIELDS_IN_ABOUTYOURSELF_CONSTRUCTOR_CV =
  'CLEAR_FIELDS_IN_ABOUTYOURSELF_CONSTRUCTOR_CV';

export const UPDATE_PI_AND_CONTACTS_IN_CONSTRUCTOR_CV = 'UPDATE_PI_AND_CONTACTS_IN_CONSTRUCTOR_CV';
export const UPDATE_FIELDS_IN_CONSTRUCTOR_CV = 'UPDATE_FIELDS_IN_CONSTRUCTOR_CV';

export const CHANGE_DIRTY_STATUS_IN_SPECIFIC_CV = 'CHANGE_DIRTY_STATUS_IN_SPECIFIC_CV';
export const RESET_DIRTY_STATUS_IN_SPECIFIC_CV = 'RESET_DIRTY_STATUS_IN_SPECIFIC_CV';
export const SPECIFIC_CV_LOADING_ON = 'SPECIFIC_CV_LOADING_ON';
export const SPECIFIC_CV_LOADING_OFF = 'SPECIFIC_CV_LOADING_OFF';
export const SPECIFIC_CV_NOT_FOUND_BY_UUID = 'SPECIFIC_CV_NOT_FOUND_BY_UUID';
export const SPECIFIC_CV_NOT_FOUND_RESET = 'SPECIFIC_CV_NOT_FOUND_RESET';

export const UPDATE_FIELDS_IN_SPECIFIC_CV = 'UPDATE_FIELDS_IN_SPECIFIC_CV';

export const UPDATE_PHOTO_IN_SPECIFIC_CV = 'UPDATE_PHOTO_IN_SPECIFIC_CV';
export const DELETE_PHOTO_IN_SPECIFIC_CV = 'DELETE_PHOTO_IN_SPECIFIC_CV';

export const FAILED_TO_SAVE = 'FAILED_TO_SAVE';
export const SAVED_SUCCESFULLY = 'SAVED_SUCCESFULLY';
