export const AUTH_IN = 'AUTH_IN';
export const AUTH_OUT = 'AUTH_OUT';

export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';

export const COUNTRIES_LOAD = 'COUNTRIES_LOAD';
export const COUNTRIES_SEARCH = 'COUNTRIES_SEARCH';

export const PHONECODES_LOAD = 'PHONECODES_LOAD';
export const PHONECODE_AND_ID_UPDATE = 'PHONECODE_AND_ID_UPDATE';

export const PHOTO_UPDATE_CABINET = 'PHOTO_UPDATE_CABINET';
export const PHOTO_UPDATE_CV = 'PHOTO_UPDATE_CV';

export const PHOTO_UPLOAD_CABINET = 'PHOTO_UPDATE_CABINET';
export const PHOTO_UPLOAD_CV = 'PHOTO_UPDATE_CV';

export const POSITIONS_LOAD = 'POSITIONS_LOAD';

export const CHANGE_DIRTY_STATUS_FORM_PD = 'CHANGE_DIRTY_STATUS_FORM_PD';
export const RESET_DIRTY_STATUS_FORM_PD = 'RESET_DIRTY_STATUS_FORM_PD';

export const PERSONALDETAILS_UPDATE = 'PERSONALDETAILS_UPDATE';

export const LINK_IS_CLICKED = 'LINK_IS_CLICKED';
export const LINK_IS_NOT_CLICKED = 'LINK_IS_NOT_CLICKED';

export const MODAL_IS_OPENED = 'MODAL_IS_OPENED';
export const MODAL_IS_CLOSED = 'MODAL_IS_CLOSED';

export const INVALID_UPLOAD = 'INVALID_UPLOAD';
export const UPLOADED = 'UPLOADED';

export const UPDATE_PERSONALINFORMATION_FROM_PD = 'UPDATE_PERSONALINFORMATION_FROM_PD';

export const ALL_CV_LOAD = 'ALL_CV_LOAD';

export const UPDATE_PERSONALINFORMATION_IN_SPECIFIC_CV =
  'UPDATE_PERSONALINFORMATION_IN_SPECIFIC_CV';
